### ISSUE TITLE
No repository for pybgapi itself?

### ISSUE THREAD

**Issue by karlp** [SiliconLabs/pybgapi-examples#1]
This is the examples, but there's no repository for pybgapi itself.  What's the expected path for issues and fixes to pybgapi?  There's no notes on https://pypi.org/project/pybgapi/#description and the "project homepage" is just www.silabs.com

**Comment by silabs-beta** [comment]
Now it's available on Github too: https://github.com/SiliconLabs/pybgapi
It reflects the current state. The links will be updated in the following patch release.
